version: 2
registries:
  npm-oob:
    type: npm-registry
    url: https://sf-db3-879c.oob.ogxing.com
    token: ${{secrets.ORG_DB_CANARY}}
    replaces-base: true
updates:
  - package-ecosystem: "npm"
    directory: "/"
    registries:
      - npm-oob
    schedule:
      interval: "daily"